(IAC-394) [AWS] update viya4-iac-aws from k8s 1.19 to 1.21
sassoftware/viya4-iac-aws pull request #119
Opened 2022-01-27 16:57 UTC by riragh

### Updated viya4-iac-aws from k8s default version from 1.19 to 1.21

2022-01-27 17:57 UTC, thpang requested changes
Two comments about provider uniformity. The rest of the changes look good.

2022-01-27 17:57 UTC, thpang commented on Dockerfile
> +ARG KUBECTL_VERSION=1.21.2
Given this is in the docker file and any 1.21 version would support the AWS 1.21 version, which happens to be 1.21.2, why would we not try and keep these the same across all cloud providers? Recently we updated Azure to used kubectl 1.21.7 I believe shown [here](https://github.com/sassoftware/viya4-iac-azure/pull/217/files).

2022-01-27 17:57 UTC, thpang commented on README.md
> +- [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/) - v1.21.2
Sync with comment above.

2022-01-27 19:41 UTC, riragh commented
Updated the K8s version from 1.21.2 to 1.21.7 for uniformity. Ready for re-review

2022-01-27 21:25 UTC, jarpat approved these changes
+1
Built an image using the dockerfile (kubectl version 1.21.7) and was able to create a 1.21 EKS cluster using the example tfvar file.

2022-01-28 15:43 UTC, thpang approved these changes

2022-01-28 15:47 UTC, merged