feat: (IAC-544) AWS - support for k8s 1.23 and dropping 1.20
sassoftware/viya4-iac-aws pull request #156
Opened 2022-09-08 15:27 UTC by dhoucgitter

## Changes
Update the kubectl version being used to 1.22.10 and the k8s version in the sample input files to v1.22. Updated README and CONFIG-VARS doc.
## Tests
See internal ticket for details and test artifacts
1. Used updated docker image to create clusters at 1.21, 1.22 and 1.23 K8s versions with successful deployments.
2. The updated kubectl version is now at 1.22.10 in the container

2022-09-08 21:38 UTC, thpang requested changes
Would like these updates to mirror the other providers. AWS now supports k8s 1.23 so we can at least keep parity that way. This would apply to the k8s version and kubectl. Kubectl can be at the same level as the other providers: 1.23.8

2022-09-09 19:02 UTC, thpang commented
Any other thoughts on this one? I would prefer to keep it aligned with the other providers given it can now support 1.23. If not we'll be updating this one and going through testing again sometime soon.

2022-09-09 19:05 UTC, Technolero commented
I'm about to deploy Production and would like to be on 1.23.

2022-09-09 19:05 UTC, dhoucgitter commented
> Any other thoughts on this one? I would prefer to keep it aligned with the other providers given it can now support 1.23. If not we'll be updating this one and going through testing again sometime soon.

sent you some thoughts to consider this morning on Teams

2022-09-12 14:52 UTC, thpang approved these changes
LGTM

2022-09-12 15:04 UTC, jarpat approved these changes
👍

2022-09-12 15:09 UTC, riragh approved these changes
LGTM

2022-09-12 15:32 UTC, merged